config/routes.rb
Rails.application.routes.draw do

  ### ACCESS + MAIN ROUTES (feel free to change these, but make sure to add a path)

  root 'access#login'

  get '/', to: 'access#login'

  get 'signup', to: 'access#new'

  post 'signup', to: 'access#create'

  get 'login', to: 'access#login'

  post 'login', to: 'access#attempt_login'

  get 'logout', to: 'access#logout'

  ### USERS ROUTES (make sure to add a path)
  get 'users', to: 'users#index'

  get 'users/:id/edit', to: 'users#edit'

  get 'users/:id', to: 'users#show'

  delete 'users/:id', to: 'users#destroy'

  patch 'users/:id/', to: 'users#update'

  ### ORDER ROUTES (you need to build these - be sure to include the user_id for each one)

  get 'users/:user_id/orders', to: 'orders#index', as: 'orders'

  get 'users/:user_id/orders/:order_id/edit', to: 'orders#edit', as: 'orders_edit'

  # add routes for a new order, showing a single order and adding a new order

  ### PRODUCTS ROUTES (you need to build these)

  get 'products', to: 'products#index', as: 'products'

end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :name, presence: true
	has_many :products
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
has_many :users, :through => :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	validates :category, presence: true
	validates :price, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :username, uniqueness: true
	validates :password, :length => {:minimum => 5 }
	has_many :orders



end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  def new
      @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.user.id
      redirect_to login_path
    else
      redirect_to login_path
    end
  end

  def login
  end

  def attempt_login
   if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end


    if !found_user
      flash.now[:alert] = "Invalid username"
      render :login

    elsif !authorized_user
      flash.now[:alert] = "Invalid password"
      render :login

    else
      session[:user_id] = authorized_user.id
      flash[:success] = "You are now logged in."
      redirect_to home_path
    end
    end
  end



  def logout
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  # Ensure a user is logged in
  def confirm_logged_in
  end

  # Stop a logged in user from going to the sign up page
  def prevent_login_signup
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :current_user
  before_action :confirm_logged_in

  def index

  end

  def show

  end

  def edit

  end

  def new

  end

  def create
    @order = Order.new(order_params)
    if params[:product_ids].present?
      for id in params[:product_ids]
        @order.order_products.build(product_id: id)
      end
    end
    if @order.save
      redirect_to orders_path, notice: "Order saved"
    else
      render :new
    end
  end

  private
  def order_params
    params.require(:order).permit(:name, :user_id)
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
  end

  def edit
  end

  def show
  end

  def new
  end

  def create

  end

  def update

  end

  def destroy

  end

  private
  def product_params
    params.require(:product).permit(:name, :category, :price)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def show

  end

  def edit

  end

   def update

   end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<%= form_for @user do |d| %>
<%= d.label  :username  %>
<%= d.text_field :username %>
<br>

<%= d.label :password %>
<%= d.text_field :password %>
<br>
<%= d.label :password_confirmation %>
<%= d.text_field :password_confirmation %>
<br>
<%= d.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

       <!-- Optional theme -->
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

</head>
<body class = "container">

<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-success" %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/orders/new.html.erb
<%= link_to("See all products", products_path) %>

<h1>Create a new order</h1>

<% if @order.errors.any? %>
  <ul class = "text-danger list-style-none">
   <%  for err in @order.errors.full_messages %>
    <li>
      <%= err%>
    </li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@order, url: orders_new_path, class: "form-horizontal") do |f|%>
  <%= f.hidden_field(:user_id, value: @current_user.id) %>

    <div class = "form-group">

      <%= f.label(:name, "Name", class: "control-label")%>

      <%= f.text_field(:name, autofocus: true, class: "form-control")%>
      </div>
  <div class = "form-group">
    <% Product.order(:name).each do |product| %>
      <div class="checkbox">
        <label>
          <%= check_box_tag('product_ids[]', product.id) %>
        <%= product.name%>
        </label>
      </div>
    <% end %>
  </div>
 <%= f.submit("Create an order", class: "btn btn-info") %>
<% end %>